[package]
name = "ecosystem"
version = "0.1.0"
authors = ["v1nam <vinamraj01@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
plotters = "0.3"
